Niloofar/documentation enhancements
deriv-com/quill-icons pull request #70
Opened 2024-02-06 09:00 UTC by niloofar-deriv

- Removed Redundant Information
- Added Insights on Functionality
- Correction of Inaccurate Details

2024-02-06 09:24 UTC, matin-deriv commented on readme.md
> +**example usage**
tiny nit :) 
```suggestion
**Usage**
```

2024-02-06 11:09 UTC, prince-deriv requested changes

2024-02-06 11:09 UTC, prince-deriv commented on readme.md
> +## OutPutters
```suggestion
## Outputters
```

2024-02-06 11:09 UTC, prince-deriv commented on readme.md
> +- Figma File Id
```suggestion
- Figma File ID
```

2024-02-07 06:32 UTC, prince-deriv approved these changes

2024-02-07 06:33 UTC, matin-deriv approved these changes

2024-02-07 06:35 UTC, merged